version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm run build
  pre_build:
    commands:
      - npm prune --production
  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $DEPLOY_BUCKET --output-template template-export.yml
      - cp -R .next _next
artifacts:
  secondary-artifacts:
    WebsiteBuild:
      type: zip
      files:
        - template-export.yml
    WebsiteBuildSource:
      files:
        - '_next/**/*'
