AWSTemplateFormatVersion: 2010-09-09

Parameters:
  RepositoryName:
    Type: String

Resources:
  SourceRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  RepositoryName:
    Value: !GetAtt SourceRepository.Name
    Export:
      Name: !Join [ '-', [!Ref 'AWS::StackName', 'SourceRepository', 'Name']]
  RepositoryArn:
    Value: !GetAtt SourceRepository.Arn
    Export:
      Name: !Join [ '-', [!Ref 'AWS::StackName', 'SourceRepository', 'Arn']]
